// Placeholder content used when Supabase is not configured (local development and tests).
// Mirrors the data after supabase/migrations/0006_company_data_dhs.sql: DHS contact data, "[Pendiente]"
// markers for what the owner has not provided, and no invented prices, FAQs, or testimonials.
import type { Category, Faq, Product, Settings, Testimonial } from "@/lib/types";

export const settings: Settings = {
  companyName: "DHS",
  tagline: "[Pendiente] Frase que resume a la empresa",
  story: "[Pendiente] Historia de la empresa",
  mission: "[Pendiente] Misión de la empresa",
  values: ["[Pendiente] Valores de la empresa"],
  certifications: [],
  clientTypes: [],
  phone: "+59157734924",
  email: "distribuidoradhs2026@gmail.com",
  whatsappNumber: "+59157734924",
  address: "[Pendiente] Dirección",
  city: "[Pendiente] Ciudad",
  mapUrl: null,
  businessHours: "[Pendiente] Horario de atención",
  serviceAreas: [],
  deliverySchedule: "[Pendiente] Días y horarios de entrega",
  minimumOrder: "[Pendiente] Pedido mínimo",
  orderingSteps: [],
};

export const categories: Category[] = [
  {
    id: "c1",
    slug: "frutas-y-verduras",
    name: "Frutas y verduras",
    description: "Productos frescos seleccionados cada día de productores nacionales.",
    imagePath: "/images/categories/frutas-y-verduras.svg",
    imageSrc: "/images/categories/frutas-y-verduras.svg",
    imageAlt: "Cajas de frutas y verduras frescas",
  },
  {
    id: "c2",
    slug: "lacteos",
    name: "Lácteos y huevos",
    description: "Leche, quesos, yogur y huevos con cadena de frío.",
    imagePath: "/images/categories/lacteos.svg",
    imageSrc: "/images/categories/lacteos.svg",
    imageAlt: "Quesos, leche y huevos",
  },
  {
    id: "c3",
    slug: "carnes-y-aves",
    name: "Carnes y aves",
    description: "Cortes de res, cerdo y pollo para cocinas profesionales.",
    imagePath: "/images/categories/carnes-y-aves.svg",
    imageSrc: "/images/categories/carnes-y-aves.svg",
    imageAlt: "Cortes de carne y pollo",
  },
  {
    id: "c4",
    slug: "abarrotes",
    name: "Abarrotes",
    description: "Arroz, azúcar, aceite, harinas y productos secos al por mayor.",
    imagePath: "/images/categories/abarrotes.svg",
    imageSrc: "/images/categories/abarrotes.svg",
    imageAlt: "Sacos de arroz y productos secos",
  },
  {
    id: "c5",
    slug: "bebidas",
    name: "Bebidas",
    description: "Aguas, jugos y refrescos para tiendas y restaurantes.",
    imagePath: "/images/categories/bebidas.svg",
    imageSrc: "/images/categories/bebidas.svg",
    imageAlt: "Botellas de agua y jugos",
  },
  {
    id: "c6",
    slug: "congelados",
    name: "Congelados",
    description: "Vegetales, papas y productos congelados listos para cocinar.",
    imagePath: "/images/categories/congelados.svg",
    imageSrc: "/images/categories/congelados.svg",
    imageAlt: "Productos congelados",
  },
];

export const products: Product[] = [
  {
    id: "p1",
    categoryId: "c1",
    name: "Tomate",
    description: "Tomate de primera, caja de 20 kg.",
    priceBob: null,
    unit: null,
    imagePath: null,
    imageSrc: null,
    imageAlt: "Tomates rojos",
  },
  {
    id: "p2",
    categoryId: "c1",
    name: "Papa holandesa",
    description: "Papa lavada, ideal para freír.",
    priceBob: null,
    unit: null,
    imagePath: null,
    imageSrc: null,
    imageAlt: "Papas",
  },
  {
    id: "p3",
    categoryId: "c1",
    name: "Frutas de temporada",
    description: "Plátano, papaya, piña y cítricos según temporada.",
    priceBob: null,
    unit: null,
    imagePath: null,
    imageSrc: null,
    imageAlt: "Frutas tropicales",
  },
  {
    id: "p4",
    categoryId: "c2",
    name: "Leche entera",
    description: "Leche pasteurizada en bolsa de 1 litro.",
    priceBob: null,
    unit: null,
    imagePath: null,
    imageSrc: null,
    imageAlt: "Leche en bolsa",
  },
  {
    id: "p5",
    categoryId: "c2",
    name: "Queso menonita",
    description: "Queso semiduro en bloque.",
    priceBob: null,
    unit: null,
    imagePath: null,
    imageSrc: null,
    imageAlt: "Bloque de queso",
  },
  {
    id: "p6",
    categoryId: "c2",
    name: "Huevos",
    description: "Huevos frescos, maple de 30 unidades.",
    priceBob: null,
    unit: null,
    imagePath: null,
    imageSrc: null,
    imageAlt: "Maple de huevos",
  },
  {
    id: "p7",
    categoryId: "c3",
    name: "Pollo entero",
    description: "Pollo fresco refrigerado.",
    priceBob: null,
    unit: null,
    imagePath: null,
    imageSrc: null,
    imageAlt: "Pollo entero",
  },
  {
    id: "p8",
    categoryId: "c3",
    name: "Carne de res",
    description: "Cortes para parrilla y guisos.",
    priceBob: null,
    unit: null,
    imagePath: null,
    imageSrc: null,
    imageAlt: "Cortes de carne de res",
  },
  {
    id: "p9",
    categoryId: "c4",
    name: "Arroz grano de oro",
    description: "Arroz nacional, quintal de 46 kg.",
    priceBob: null,
    unit: null,
    imagePath: null,
    imageSrc: null,
    imageAlt: "Saco de arroz",
  },
  {
    id: "p10",
    categoryId: "c4",
    name: "Aceite vegetal",
    description: "Aceite de soya, bidón de 5 litros.",
    priceBob: null,
    unit: null,
    imagePath: null,
    imageSrc: null,
    imageAlt: "Bidón de aceite",
  },
  {
    id: "p11",
    categoryId: "c4",
    name: "Azúcar",
    description: "Azúcar blanca, quintal de 46 kg.",
    priceBob: null,
    unit: null,
    imagePath: null,
    imageSrc: null,
    imageAlt: "Saco de azúcar",
  },
  {
    id: "p12",
    categoryId: "c5",
    name: "Agua de mesa",
    description: "Botellas de 2 litros, paquete de 6.",
    priceBob: null,
    unit: null,
    imagePath: null,
    imageSrc: null,
    imageAlt: "Botellas de agua",
  },
  {
    id: "p13",
    categoryId: "c5",
    name: "Jugos naturales",
    description: "Jugos de frutas en envase de 1 litro.",
    priceBob: null,
    unit: null,
    imagePath: null,
    imageSrc: null,
    imageAlt: "Jugos en envase",
  },
  {
    id: "p14",
    categoryId: "c6",
    name: "Papas prefritas",
    description: "Papas bastón congeladas, bolsa de 2,5 kg.",
    priceBob: null,
    unit: null,
    imagePath: null,
    imageSrc: null,
    imageAlt: "Papas prefritas congeladas",
  },
];

export const faqs: Faq[] = [];

export const testimonials: Testimonial[] = [];
